# Generated by Django 4.1.5 on 2023-03-07 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_student_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='pincode',
            new_name='Phone',
        ),
    ]
