# Generated by Django 4.1.5 on 2023-03-09 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_student_teacher_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profile_img',
            field=models.FileField(default='', upload_to='images/'),
        ),
    ]
