# Generated by Django 4.1.5 on 2023-03-06 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='dob',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='email',
            field=models.CharField(default='', max_length=50),
        ),
    ]
